apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins-ha.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins-ha.labels" . | nindent 4 }}
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins HA Setup - Managed by Helm"
      numExecutors: 2
      mode: NORMAL
      quietPeriod: 5
      scmCheckoutRetryCount: 0
      disableRememberMe: false
      labelString: "master"
    security:
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: triggeringUsersAuthorizationStrategy
    unclassified:
      location:
        url: "https://{{ .Values.ingress.host }}/"
        adminAddress: "admin@{{ .Values.ingress.host }}"
