apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins-ha.fullname" . }}-admin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins-ha.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.jenkins.adminUser | b64enc | quote }}
  password: {{ .Values.jenkins.adminPassword | b64enc | quote }}
