apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jenkins-ha.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins-ha.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jenkins-ha.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins-ha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "jenkins-ha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: jenkins
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "{{ .Values.jenkins.javaOpts }} -Djenkins.install.runSetupWizard=false"
        - name: JENKINS_OPTS
          value: "--httpPort=8080"
        - name: JENKINS_ADMIN_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "jenkins-ha.fullname" . }}-admin
              key: username
        - name: JENKINS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "jenkins-ha.fullname" . }}-admin
              key: password
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: jenkins-config
          mountPath: /var/jenkins_home/jenkins.yaml
          subPath: jenkins.yaml
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: {{ include "jenkins-ha.fullname" . }}-shared-pvc
      - name: jenkins-config
        configMap:
          name: {{ include "jenkins-ha.fullname" . }}-config
