global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
rule_files:
  - alerts/jenkins.yml
