apiVersion: v2
name: jenkins-ha
description: High Availability Jenkins deployment
type: application
version: 1.0.0
appVersion: "2.426.3-lts"
keywords:
  - jenkins
  - ci
  - cd
  - devops
home: https://github.com/GITHUB_USERNAME/jenkins-ha-migration
sources:
  - https://github.com/GITHUB_USERNAME/jenkins-ha-migration
maintainers:
  - name: DevOps Team
    email: devops@example.com
dependencies: []
